# Crawler config file

[site]
# true = AlexaTopSitesURL + manualSeedURL
# false = manualSeedURL
useAlexaTopSites = true
 
AlexaTopSitesURL = "https://www.alexa.com/topsites/countries/TW"
manualSeedURL = ["https://www.npr.org", "https://edition.cnn.com"]