# Crawler config file

[site]
# true = AlexaTopSitesURL 
# false = manualSeedURL
useAlexaTopSites = false
 
AlexaTopSitesURL = "https://www.alexa.com/topsites/countries/TW" # issues with no leading portocal... QQ
# manualSeedFile = "data/seedingSites.txt"
# manualSeedFile = "data/seedingSitesSubset.txt"
# manualSeedFile = "data/small.txt"
manualSeedFile = "data/test.txt"

[system]
maxGoRountinesPerSite = 2

maxDistinctPagesToFetchPerSite = 50000
maxTotalPagesToFetch = 2500000

timeout = 5 # page load timeout in seconds
timeInterval = 5 # idle time between fetches in seconds

reseedInterval = 24 # in hours

[output]

slowAction = 10000000000 # ns (1e-9)

seedfile = "data/currentRunSeedSite.txt"
parsingResult = "data/parsingResult.txt"