# Crawler config file

[site]
# true = AlexaTopSitesURL 
# false = manualSeedURL
useAlexaTopSites = false
 
AlexaTopSitesURL = "https://www.alexa.com/topsites/countries/TW" # issues with no leading protocal... QQ
# manualSeedFile = "data/seedingSites.txt"
manualSeedFile = "data/small.txt"

[output]
seedfile = "data/currentRunSeedSite.txt"