# Crawler config file

[site]
# true = AlexaTopSitesURL 
# false = manualSeedURL
useAlexaTopSites = false
 
AlexaTopSitesURL = "https://www.alexa.com/topsites/countries/TW" # issues with no leading portocal... QQ
manualSeedFile = "data/seedingSites.txt"
# manualSeedFile = "data/seedingSitesSubset.txt"
# manualSeedFile = "data/small.txt"
# manualSeedFile = "data/test.txt"

[system]
maxGoRountinesPerSite = 2

maxDistinctPagesToFetchPerSite = 50000
maxTotalPagesToFetch = 2500000

timeout = 5 # page load timeout in seconds
minFetchTimeInterval = 5 # idle time between fetches in seconds

reseedInterval = 24 # in hours

[chromedp]
# /opt/google/chrome
# /usr/bin/google-chrome
# /opt/google/chrome/google-chrome --headless --remote-debugging-port=9222 --disable-gpu
headlessMode = true

[output]

slowAction = 10000000000 # ns (1e-9)

# please create the folder manually!

seedfile = "data/currentRunSeedSite.txt"
pageSourcePath = "pageSource/"
screenshotPath = "screenshot/"